### ISSUE TITLE
Uncaught error stops update loop

### ISSUE THREAD

**Issue by micthiesen** [micthiesen/spotify-my-slack#1]
```
Aug 13 10:28:40 spotify-my-slack app/web.1: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 10.231.86.239:5432 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:116:24) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:123:14) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at Connection.emit (events.js:182:13) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:71:10) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at Socket.emit (events.js:182:13) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at emitErrorNT (internal/streams/destroy.js:82:8) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) 
Aug 13 10:28:40 spotify-my-slack app/web.1:     at process._tickCallback (internal/process/next_tick.js:63:19) 
Aug 13 10:28:40 spotify-my-slack app/web.1: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 99) 
Aug 13 10:28:40 spotify-my-slack app/web.1: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by micthiesen** [comment]
It might be useful to crash in these situations: https://medium.com/@dtinth/making-unhandled-promise-rejections-crash-the-node-js-process-ffc27cfcc9dd

**Comment by micthiesen** [comment]
We'll see if 27b0fff handles this situation as expected
